<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-88V4A8K" failures="3" tests="8" name="SeleniumTests" time="92.814" errors="0" timestamp="2024-04-18T15:48:46 IST">
  <testcase classname="TestNGConcepts.Login" name="registration" time="0.008">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNGConcepts.Login.registration(Login.java:119)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- registration -->
  <testcase classname="TestNGConcepts.Login" name="registration2" time="0.006"/>
  <testcase classname="TestNGConcepts.Login" name="loginWithValidCredentials" time="4.742"/>
  <testcase classname="TestNGConcepts.Login" name="loginWithValidCredentials" time="10.014">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestNGConcepts.Login.loginWithValidCredentials() didn&amp;apos;t finish within the time-out 10000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNGConcepts.Login.loginWithValidCredentials() didn't finish within the time-out 10000
at java.base@17.0.7/java.lang.Thread.sleep(Native Method)
at app//TestNGConcepts.YourStore.clickOnMyAccountIcon(YourStore.java:25)
at app//TestNGConcepts.Login.loginWithValidCredentials(Login.java:31)
at java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- loginWithValidCredentials -->
  <testcase classname="TestNGConcepts.Login" name="loginWithValidCredentials" time="4.829"/>
  <testcase classname="TestNGConcepts.Login" name="loginWithInValidEmailId" time="0.0">
    <skipped/>
  </testcase> <!-- loginWithInValidEmailId -->
  <testcase classname="TestNGConcepts.Login" name="loginWithInValidCredentials" time="0.0">
    <skipped/>
  </testcase> <!-- loginWithInValidCredentials -->
  <testcase classname="TestNGConcepts.Login" name="loginWithInValidPassword" time="4.572">
    <failure type="java.lang.AssertionError" message="expected [My Account] but found [Account Login]">
      <![CDATA[java.lang.AssertionError: expected [My Account] but found [Account Login]
at day31.POM.MyAccount.validateLoginStatus(MyAccount.java:17)
at TestNGConcepts.Login.loginWithInValidPassword(Login.java:90)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInValidPassword -->
</testsuite> <!-- SeleniumTests -->
